# Generated by Django 5.1.5 on 2025-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='Question_1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Question_2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='survey',
            name='Question_3',
            field=models.CharField(max_length=100),
        ),
    ]
